feat: apply stopwords by language
appbaseio/reactivesearch-api pull request #213
Opened 2021-11-12 07:32 UTC by bietkul

#### What does this do / why do we need it?
https://www.notion.so/appbase/Arc-Suggestions-API-enhancements-2a4c26df77d44a77b751d9e13cf4cb0f

https://www.loom.com/share/34833ddd8e4d4a94bebfc382413af59c

https://www.loom.com/share/9c93ff72089843189f4a22edbf19b2be

#### What should your reviewer look out for in this PR?

#### Which issue(s) does this PR fix?

#### If this PR affects any API reference documentation, please share the updated endpoint references

2021-11-13 09:21 UTC, siddharthlatest commented on plugins/querytranslate/languages.go
> +// languages supported by stopword package
```suggestion
// languages supported by stopwords package
```

2021-11-13 09:22 UTC, siddharthlatest commented on plugins/querytranslate/suggestions.go
> +										if len(strings.Trim(cleanContent, " ")) == 0 {
```suggestion
										if len(strings.TrimSpace(cleanContent)) == 0 {
```

2021-11-13 09:23 UTC, siddharthlatest commented on plugins/querytranslate/suggestions.go
> +										if len(strings.Trim(cleanContent, " ")) == 0 {
TrimSpace removes all whitespaces instead of explicitly removing only space.

2021-11-13 10:15 UTC, siddharthlatest requested changes
@bietkul 

- [ ] Add the documentation reference for the `searchLanguage` property and valid values.
- [ ] It seems that this only applies for suggestions API, it should apply for search API as well.

**Also a question:**
- If searchLanguage isn't explicitly passed in RS API, will this take the search relevance's language for stopwords? It should be this way.

2021-11-15 06:55 UTC, bietkul commented
@siddharthlatest Docs PR https://github.com/appbaseio/Docs/pull/246

> If searchLanguage isn't explicitly passed in RS API, will this take the search relevance's language for stopwords? It should be this way.

Yes, review this PR https://github.com/appbaseio-confidential/arc-noss/pull/230

2021-11-16 12:19 UTC, siddharthlatest approved these changes
lgtm (y)

2021-11-16 12:21 UTC, merged