feat: add support for pivot facets query
appbaseio/reactivesearch-api pull request #326
Opened 2022-08-01 13:48 UTC by bietkul

#### What does this do / why do we need it?
https://www.notion.so/appbase/Pivot-Facets-Hierarchical-dde19c6f5b7b4fc8ae3d7511f83def55

https://www.loom.com/share/36029bf478ba44d1bcbefa96f2ec72ad
#### What should your reviewer look out for in this PR?

#### Which issue(s) does this PR fix?

#### If this PR affects any API reference documentation, please share the updated endpoint references

2022-08-01 13:50 UTC, siddharthlatest commented on plugins/querytranslate/translate_test.go
> -	Convey("with multiple dataFields for search", t, func() {
@bietkul Why remove this test?

2022-08-01 13:51 UTC, siddharthlatest requested changes
- [ ] Share the generated query for the component (playground link or cURL is good)
- [ ] Share the generated query for the dependent component (playground link or cURL is good)

- [ ] Code walkthrough

- [ ] Why is multiple data fields in search test removed?

2022-08-01 16:20 UTC, bietkul commented
`cURL` request for both `aggs` and `results`
```
curl --location --request POST 'http://foo:bar@localhost:8000/best-buy-dataset/_reactivesearch/validate' \
--header 'Content-Type: application/json' \
--data-raw '{
    "query": [
        {
            "id": "t",
            "dataField": [
                "class.keyword",
                "subclass.keyword"
            ],
            "type": "term",
            "size": 0,
            "aggregationSize": 2,
            "sortBy": "count",
            "value": [
                "DVD SOFTWARE",
                "COMPACT DISC > VINYL"
            ]
        },
        {
            "id": "result",
            "react": {
                "and": "t"
            },
            "size": 5,
            "defaultQuery": {
                "track_total_hits": true
            },
            "includeFields": ["class", "subclass"]
        }
    ]
}'
```

2022-08-02 11:01 UTC, siddharthlatest requested changes
- [ ] Edge case: queryFormat value change should change the query
https://www.loom.com/share/86139102401040399c13e5a881a398e2

2022-08-03 09:25 UTC, siddharthlatest commented on plugins/querytranslate/term_query_test.go
> +	convey.Convey("pivot facets: results query with queryFormat as or", t, func() {
```suggestion
	convey.Convey("pivot facets: results query with queryFormat as and", t, func() {
```

2022-08-03 09:27 UTC, siddharthlatest approved these changes

2022-08-03 09:27 UTC, merged