feat: add template for searchable fields
appbaseio/reactivesearch-api pull request #86
Opened 2020-03-24 14:33 UTC by lakhansamani

### What does this do / why do we need it?

* Add mappings & settings in the default v7 template for searchable fields. i.e. it will add `.search`, `.autosuggest` and `.keyword` fields
* Remove check if the template exists. This will help us in updating template any time we want and ES also allows updating template with the same name.

### What should your reviewer look out for in this PR?

### Do you need help or clarification on anything?

### Which issue(s) does this PR fix?

2020-03-24 15:30 UTC, bietkul requested changes

2020-03-24 15:30 UTC, bietkul commented on util/es_template.go
> +			"max_shingle_diff": 8,
@lakhansamani Can you fix the formatting?

2020-03-24 15:35 UTC, siddharthlatest requested changes

2020-03-24 15:35 UTC, siddharthlatest commented on util/es_template.go
> +						"autosuggest": {
@lakhansamani Also, what about lang and synonyms fields? This isn't complete.

2020-03-25 07:11 UTC, siddharthlatest requested changes
The other changes (mappings) should get applied for both v6 and v7.

For synonyms, we should also apply `lowercase`.

2020-03-25 10:48 UTC, siddharthlatest approved these changes

2020-03-25 10:49 UTC, merged